site_name: docstr - A document string minor mode
site_description: Document String tool for Emacs
site_url: https://jcs-elpa.github.io/docstr
site_author: jcs090218@gmail.com

nav:
  - Home:
    - Overview: README.md
  - Languages:
    - page/languages.md
    - ActionScript: page/langs/actionscript.md
    - C/C++: page/langs/cpp.md
    - C#: page/langs/chsarp.md
    - Go: page/langs/go.md
    - Groovy: page/langs/groovy.md
    - Java: page/langs/java.md
    - JavaScript: page/langs/javascript.md
    - Lua: page/langs/lua.md
    - PHP: page/langes/php.md
    - Python: page/langes/python.md
    - Rust: page/langes/rust.md
    - Rust: page/langes/rust.md
    - Scala: page/langes/scala.md
    - TypeScript: page/langes/typescript.md

extra_css:
  - stylesheets/layout.css
  - stylesheets/members.css

theme:
  name: material
  logo: examples/logo-mini.png
  favicon: examples/logo-mini.png
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/jcs-elpa/docstr
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/jcs090218

repo_name: jcs-elpa/docstr
repo_url: https://github.com/jcs-elpa/docstr

markdown_extensions:
  - pymdownx.superfences
  - codehilite
  - meta
  - toc:
      permalink: '#'
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search
  - awesome-pages
  - git-revision-date-localized
  - rss

google_analytics:
  - UA-165661257-1
  - auto
