name: Docs

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Move README.md
        with:
          args: -s CHANGELOG.org -t gfm -o docs/page/CHANGELOG.md
          cp -rf README.md docs/page/README.md

      - name: MkDocs
        run: |
          cp -rf README.md docs etc

          docker login docker.pkg.github.com --username $GITHUB_ACTOR --password ${{ secrets.GITHUB_TOKEN }}
          docker run --rm -v ${PWD}:/docs docker.pkg.github.com/jcs-elpa/docs-image/docs-image -- build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
